# User config
author: "rajat19"
tagline: "VS Code Terminal Colors"
email: "rajatsri94@gmail.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/"

markdown: kramdown

# Site config
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed